# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/camera

PRODUCT_COPY_FILES += \
    vendor/oneplus/camera/proprietary/etc/permissions/com.oneplus.camera.service.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.oneplus.camera.service.xml \
    vendor/oneplus/camera/proprietary/system_ext/etc/permissions/privapp-permissions-oem-system_ext.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-oem-system_ext.xml \
    vendor/oneplus/camera/proprietary/system_ext/lib/libopcameralib-em.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/libopcameralib-em.so \
    vendor/oneplus/camera/proprietary/system_ext/lib64/libopcameralib-em.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libopcameralib-em.so \
    vendor/oneplus/camera/proprietary/vendor/lib/libswregistrationalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libswregistrationalgo.so \
    vendor/oneplus/camera/proprietary/vendor/lib64/libswregistrationalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libswregistrationalgo.so

PRODUCT_PACKAGES += \
    OnePlusCameraService \
    OnePlusCamera \
    OnePlusGallery
